JBT 20250113 update  the CircleCI pipe

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -31,6 +31,20 @@ jobs:
             else
               echo "Error: The build directory does not exist."
               exit 1
+            fi      
+      - run:
+          name: "Build the app"
+          command: |
+            cmake ..
+            cmake --build .
+      - run:
+          name: "Check if build directory exists and log"
+          command: |
+            if [ -f "ArcadeGamesProject" ]; then
+              echo "The ArcadeGamesProject fiel exists."
+            else
+              echo "Error: The ArcadeGamesProject file does not exist."
+              exit 1
             fi
       - run:
           name: "Say hello"
